name: instagram_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  copy_with_extension_gen: ^5.0.4
  json_serializable: ^6.8.0
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.5
  firebase_database: ^10.5.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  get_it: ^7.7.0
  flutter_randomcolor: ^1.0.15
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  intl_phone_field: ^3.0.1
  flutter_svg: ^2.0.10+1
  modal_bottom_sheet: ^3.0.0
  cached_network_image: ^3.3.1
  uuid: ^4.4.2
  # dash_chat_2: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
